# Generated by Django 5.2 on 2026-08-26 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('issue_date_text', models.CharField(blank=True, help_text="e.g. '2024'", max_length=50)),
                ('credential_url', models.URLField(blank=True)),
                ('credential_id', models.CharField(blank=True, max_length=150)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['display_order', '-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(max_length=200)),
                ('grade', models.CharField(blank=True, help_text='e.g. CGPA / Percentage', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('period_text', models.CharField(blank=True, help_text="e.g. '2021 - 2025'", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Key coursework or academic highlights')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['display_order', '-end_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('employment_type', models.CharField(choices=[('internship', 'Internship'), ('freelance', 'Freelance / Contract'), ('full_time', 'Full-time'), ('part_time', 'Part-time')], default='internship', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='Summary of responsibilities and achievements (supports bullet lines)')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['display_order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Parmeet Singh', max_length=100)),
                ('headline', models.CharField(default="Building digital products, working with data, and exploring what's next.", max_length=255)),
                ('subheadline', models.TextField(default="I'm a Computer Science graduate specializing in AI & Data Science, building web applications, exploring data-driven solutions, and working on digital projects for businesses.")),
                ('bio_short', models.TextField(default='Parmeet is a Computer Science graduate with a background in AI & Data Science who enjoys building practical software and experimenting across different areas of technology. He is currently exploring the intersection of Software Development, Data, and Digital Products.')),
                ('bio_full', models.TextField(blank=True, default='I am an early-career technologist passionate about software engineering, data analytics, and digital product creation. My background in Computer Science with specialization in AI & Data Science has equipped me with strong problem-solving fundamentals, modern full-stack development skills (Python, Django, JavaScript), and data exploration capabilities. Rather than claiming senior expertise in everything, I focus on hands-on execution: understanding real-world user needs, writing clean code, analyzing information thoughtfully, and delivering functional digital experiences.')),
                ('email', models.EmailField(default='contact@parmeetsingh.dev', max_length=254)),
                ('location', models.CharField(default='Punjab, India', max_length=100)),
                ('github_url', models.URLField(default='https://github.com/parmeetsingh')),
                ('linkedin_url', models.URLField(default='https://linkedin.com/in/parmeetsingh')),
                ('is_available_for_work', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Site Profile',
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Parmeet Singh - Resume', max_length=150)),
                ('file', models.FileField(upload_to='resumes/')),
                ('is_active', models.BooleanField(default=True, help_text='Only active resume will be served to recruiters')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume Document',
                'verbose_name_plural': 'Resume Documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('short_summary', models.CharField(max_length=255)),
                ('full_description', models.TextField()),
                ('what_included', models.TextField(help_text='Bullet points of what is included (newline separated)')),
                ('who_its_for', models.TextField(help_text='Ideal target audience or business type')),
                ('what_delivered', models.TextField(help_text='Deliverables and outcome')),
                ('icon', models.CharField(default='code', help_text='Icon identifier (e.g. layout, code, database, refresh-cw, smartphone, layers)', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('languages', 'Programming Languages'), ('backend', 'Backend & Frameworks'), ('frontend', 'Frontend & UI'), ('data_ai', 'Data, Analytics & AI'), ('database', 'Databases'), ('tools', 'Tools & DevOps')], default='backend', max_length=30)),
                ('badge_color', models.CharField(blank=True, default='indigo', max_length=30)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('tagline', models.CharField(help_text='Short one-line elevator pitch', max_length=255)),
                ('featured_image', models.ImageField(upload_to='projects/')),
                ('overview', models.TextField(help_text='What real-world problem this project solves')),
                ('what_i_built', models.TextField(help_text="Detailed explanation of Parmeet's actual contribution and architecture")),
                ('key_features', models.TextField(help_text='List key features (separated by newlines)')),
                ('challenges_learning', models.TextField(help_text='Technical challenges encountered and what was learned')),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL')),
                ('live_url', models.URLField(blank=True, help_text='Live working demo URL')),
                ('client_type', models.CharField(choices=[('personal', 'Personal Project'), ('freelance', 'Freelance / Client Work'), ('academic', 'Academic / Research'), ('open_source', 'Open Source')], default='personal', max_length=30)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on Homepage')),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.projectcategory')),
                ('technologies', models.ManyToManyField(related_name='projects', to='portfolio.technology')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Project Screenshot',
                'verbose_name_plural': 'Project Screenshots',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, help_text="e.g. 'Core Stack', 'Data Pipelines', 'APIs'", max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
