# Generated by Django 5.2.17 on 2026-09-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_profile_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='+91 9318406016', max_length=30),
        ),
    ]
