# Generated by Django 5.2.17 on 2026-09-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_type',
            field=models.CharField(choices=[('personal', 'Personal Project'), ('freelance', 'Freelance / Client Work'), ('prototype', 'Concept Prototype / Sample Build'), ('academic', 'Academic / Research'), ('open_source', 'Open Source')], default='personal', max_length=30),
        ),
    ]
